name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run linter
      run: |
        if npm run lint --silent > /dev/null 2>&1; then
          npm run lint
        else
          echo "Lint script not found, skipping..."
        fi

    - name: Build project
      run: |
        if npm run build --silent > /dev/null 2>&1; then
          npm run build
        else
          echo "Build script not found, skipping..."
        fi