name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel
        if: vars.DEPLOY_TARGET == 'vercel' || vars.DEPLOY_TARGET == 'all'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

      - name: Deploy to Render
        if: vars.DEPLOY_TARGET == 'render' || vars.DEPLOY_TARGET == 'all'
        run: |
          if [ ! -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          fi

      - name: Deploy to Fly.io
        if: vars.DEPLOY_TARGET == 'fly' || vars.DEPLOY_TARGET == 'all'
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest
      
      - name: Deploy to Fly.io
        if: vars.DEPLOY_TARGET == 'fly' || vars.DEPLOY_TARGET == 'all'
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}